$$import: _catalog.yaml

encoder:
  representations: [uid_hierarchical]

decoder:
  targets:
    - representation: uid_hierarchical
      decoding:
        mode: hierarchical
        topk: ${uid_cluster_topk:20}$
