data:
  name: ${data}$
  levels: ${uid_cluster_levels:auto}$

word2vec:
  vector_size: ${cluster_vector_size:64}$
  window: ${cluster_window:5}$
  patience: ${cluster_patience:5}$
  sg: ${cluster_sg:1}$
  negative: ${cluster_negative:5}$
  min_count: ${cluster_min_count:1}$
  workers: ${cluster_workers:4}$
  seed: ${cluster_seed:42}$

cluster:
  batch_size: ${cluster_batch_size:4096}$
  max_iter: ${cluster_max_iter:100}$
  n_init: ${cluster_n_init:10}$
