name: qwen08b_grid1_ebs64
poll_interval_seconds: 15
effective_batch_size: 64
backend:
  uri: https://api.seco.qijiong.work
  auth_token: 5ec0mmender5
notificator:
  name: Seco
  token: yyTNY6CVpSxPP581cVJLBzZr6gf71SAy
  bark: https://api.day.app/p7eciGfLv6oNuwQktkLE5Q/
experiments:
- name: qwen08b_grid1_lr3e-05_constant_wu0_uid_raf_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 3.0e-05
    lr_scheduler: constant
    warmup_ratio: 0.0
    data: raf
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: qwen08b_grid1_lr3e-05_constant_wu0_uid_raf_qwen35th08b_uid+text2uid_flat
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 3.0e-05
    lr_scheduler: constant
    warmup_ratio: 0.0
    data: raf
    model: qwen35th08b
    task_type: uid
    repr_type: uid+text
    uid_decoding: flat
- name: qwen08b_grid1_lr3e-05_constant_wu0_sid_raf_qwen35th08b_sid2sid_pretrain-multimodal_rqvae_recon
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 3.0e-05
    lr_scheduler: constant
    warmup_ratio: 0.0
    sid_embedding_model: pretrain-multimodal
    sid_codebook_size: 128
    data: raf
    model: qwen35th08b
    task_type: sid
    repr_type: sid
    repr_source_model: pretrain-multimodal
    sid_coder: rqvae
    sid_export: recon
- name: qwen08b_grid1_lr3e-05_cosine_wu0.1_uid_raf_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 3.0e-05
    lr_scheduler: cosine
    warmup_ratio: 0.1
    data: raf
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: qwen08b_grid1_lr3e-05_cosine_wu0.1_uid_raf_qwen35th08b_uid+text2uid_flat
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 3.0e-05
    lr_scheduler: cosine
    warmup_ratio: 0.1
    data: raf
    model: qwen35th08b
    task_type: uid
    repr_type: uid+text
    uid_decoding: flat
- name: qwen08b_grid1_lr3e-05_cosine_wu0.1_sid_raf_qwen35th08b_sid2sid_pretrain-multimodal_rqvae_recon
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 3.0e-05
    lr_scheduler: cosine
    warmup_ratio: 0.1
    sid_embedding_model: pretrain-multimodal
    sid_codebook_size: 128
    data: raf
    model: qwen35th08b
    task_type: sid
    repr_type: sid
    repr_source_model: pretrain-multimodal
    sid_coder: rqvae
    sid_export: recon
- name: qwen08b_grid1_lr0.0001_constant_wu0_uid_raf_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 0.0001
    lr_scheduler: constant
    warmup_ratio: 0.0
    data: raf
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: qwen08b_grid1_lr0.0001_constant_wu0_uid_raf_qwen35th08b_uid+text2uid_flat
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 0.0001
    lr_scheduler: constant
    warmup_ratio: 0.0
    data: raf
    model: qwen35th08b
    task_type: uid
    repr_type: uid+text
    uid_decoding: flat
- name: qwen08b_grid1_lr0.0001_constant_wu0_sid_raf_qwen35th08b_sid2sid_pretrain-multimodal_rqvae_recon
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 0.0001
    lr_scheduler: constant
    warmup_ratio: 0.0
    sid_embedding_model: pretrain-multimodal
    sid_codebook_size: 128
    data: raf
    model: qwen35th08b
    task_type: sid
    repr_type: sid
    repr_source_model: pretrain-multimodal
    sid_coder: rqvae
    sid_export: recon
- name: qwen08b_grid1_lr0.0001_cosine_wu0.1_uid_raf_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 0.0001
    lr_scheduler: cosine
    warmup_ratio: 0.1
    data: raf
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: qwen08b_grid1_lr0.0001_cosine_wu0.1_uid_raf_qwen35th08b_uid+text2uid_flat
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 0.0001
    lr_scheduler: cosine
    warmup_ratio: 0.1
    data: raf
    model: qwen35th08b
    task_type: uid
    repr_type: uid+text
    uid_decoding: flat
- name: qwen08b_grid1_lr0.0001_cosine_wu0.1_sid_raf_qwen35th08b_sid2sid_pretrain-multimodal_rqvae_recon
  args:
    main_metric: ndcg@10
    epochs: 20
    patience: 5
    weight_decay: 0.01
    seed: 42
    use_lora: 'true'
    freeze_backbone: 'true'
    lora_rank: 8
    lora_alpha: 32
    lora_dropout: 0.05
    lora_target_modules: all-linear
    learning_rate: 0.0001
    lr_scheduler: cosine
    warmup_ratio: 0.1
    sid_embedding_model: pretrain-multimodal
    sid_codebook_size: 128
    data: raf
    model: qwen35th08b
    task_type: sid
    repr_type: sid
    repr_source_model: pretrain-multimodal
    sid_coder: rqvae
    sid_export: recon
