name: recif_scaling
poll_interval_seconds: 15
effective_batch_size: 64
experiments:
- name: recif_scaling_scratch_uid_rv1_scratch_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: rv1
    model: scratch
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_scratch_uid_rv1_scratch_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: rv1
    model: scratch
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_scratch_uid_rv2_scratch_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: rv2
    model: scratch
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_scratch_uid_rv2_scratch_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: rv2
    model: scratch
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_scratch_uid_rv5_scratch_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: rv5
    model: scratch
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_scratch_uid_rv5_scratch_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: rv5
    model: scratch
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_scratch_uid_rv10_scratch_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: rv10
    model: scratch
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_scratch_uid_rv10_scratch_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: rv10
    model: scratch
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_scratch_uid_ra1_scratch_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: ra1
    model: scratch
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_scratch_uid_ra1_scratch_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: ra1
    model: scratch
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_scratch_uid_ra2_scratch_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: ra2
    model: scratch
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_scratch_uid_ra2_scratch_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: ra2
    model: scratch
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_scratch_uid_ra5_scratch_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: ra5
    model: scratch
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_scratch_uid_ra5_scratch_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: ra5
    model: scratch
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_scratch_uid_ra10_scratch_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: ra10
    model: scratch
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_scratch_uid_ra10_scratch_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: ra10
    model: scratch
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_rv1_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: rv1
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_rv1_qwen35th08b_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: rv1
    model: qwen35th08b
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_rv2_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: rv2
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_rv2_qwen35th08b_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: rv2
    model: qwen35th08b
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_rv5_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: rv5
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_rv5_qwen35th08b_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: rv5
    model: qwen35th08b
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_rv10_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: rv10
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_rv10_qwen35th08b_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: rv10
    model: qwen35th08b
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_ra1_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: ra1
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_ra1_qwen35th08b_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: ra1
    model: qwen35th08b
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_ra2_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: ra2
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_ra2_qwen35th08b_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: ra2
    model: qwen35th08b
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_ra5_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: ra5
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_ra5_qwen35th08b_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: ra5
    model: qwen35th08b
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_ra10_qwen35th08b_uid2uid_flat
  args:
    main_metric: ndcg@10
    data: ra10
    model: qwen35th08b
    task_type: uid
    repr_type: uid
    uid_decoding: flat
- name: recif_scaling_qwen35th08b_uid_ra10_qwen35th08b_uid+embedding2uid_pretrain-multimodal_flat
  args:
    main_metric: ndcg@10
    data: ra10
    model: qwen35th08b
    task_type: uid
    repr_type: uid+embedding
    repr_source_model: pretrain-multimodal
    uid_decoding: flat
